### ISSUE TITLE
We should add a better way to select between running different parts of the energy equation

### ISSUE THREAD

**Issue by maplesond** [maplesond/msa2qubo#1]
The reason so this ticket is that currently we end up commenting or uncommenting lines to check between different parts of the equation.  This is starting to cause problems because the QUBO now has lots of binary variables when including E2.  So restricting to a smaller run should not just shrink the matrix size but also highlight the reduced number of max_diagonals option marked at the top of the QUBO itself.

As I see it there are only two modes worth considering:

E=E0+E1 and E=E0+E1+E2.

This option should be selectable at both the qmsa, and msa2qubo command line.

**Comment by ljyanesm** [comment]
This should be resolved by the previous commit, mind doing a quick code review? @maplesond

**Comment by maplesond** [comment]
Great. I'll try to take a look at this tomorrow.

**Comment by maplesond** [comment]
Looks fine to me!  Thanks for sorting this out.
